---

- name: test downloads
  script: downloads.sh

- name: concatenate logs
  shell: cat downloads_1.log downloads_2.log downloads_3.log > downloads.log
  args:
    chdir: /tmp

- name: calculate sha512 checksum of logfile
  stat:
    checksum_algorithm: sha512
    get_checksum: true
    get_attributes: false
    get_md5: false
    get_mime: false
    path: /tmp/downloads.log
  register: logfile

- name: save checksum to file
  local_action:
    copy content="{{ logfile.stat.checksum }}" dest="../logs/{{inventory_hostname}}/downloads.log.sha512"
  become: no

- name: retrieve log
  fetch:
    src: /tmp/downloads.log
    dest: ../logs/{{inventory_hostname}}/downloads.log
    flat: yes

