---

- name: download mariadb
  get_url:
    url: https://downloads.mariadb.com/MariaDB/mariadb-{{mariadb_version}}/source/mariadb-{{mariadb_version}}.tar.gz
    dest: /tmp/mariadb-{{mariadb_version}}.tar.gz

- name: uncompress mariadb
  unarchive:
    src: /tmp/mariadb-{{mariadb_version}}.tar.gz
    dest: /tmp
    copy: no

- name: install packages needed to build mariadb
  apt:
    name: "{{item}}"
    state: present
    update_cache: yes
    install_recommends: no
  with_items:
    - bison
    - make
    - cmake
    - g++
    - gcc
    - git
    - libaio-dev
    - libcurl4-gnutls-dev
    - libevent-dev
    - libgnutls28-dev
    - libjemalloc-dev
    - libncurses-dev
    - libxml2-dev
    - zlib1g-dev

- name: configure the mariadb build
  shell: cmake . -DBUILD_CONFIG=mysql_release
  args:
    chdir: /tmp/mariadb-{{mariadb_version}}

- name: compile mariadb
  shell: (time -p make) > /tmp/compiler.log 2>&1
  args:
    executable: /bin/bash
    chdir: /tmp/mariadb-{{mariadb_version}}

- name: retrieve log
  fetch:
    src: /tmp/compiler.log
    dest: ../logs/{{inventory_hostname}}/compiler.log
    flat: yes

- name: remove mariadb files
  file:
    path: "{{item}}"
    state: absent
  with_items:
    - /tmp/mariadb-{{mariadb_version}}
    - /tmp/mariadb-{{mariadb_version}}.tar.gz

- name: remove installed packages
  apt:
    name: "{{item}}"
    autoremove: yes
    purge: yes
    state: absent
  with_items:
    - bison
    - make
    - cmake
    - g++
    - gcc
    - git
    - libaio-dev
    - libcurl4-gnutls-dev
    - libevent-dev
    - libgnutls28-dev
    - libjemalloc-dev
    - libncurses-dev
    - libxml2-dev
    - zlib1g-dev
