---

- name: install dmidecode & lshw & inxi & hwinfo
  apt:
    name: "{{item}}"
    state: latest
    update_cache: yes
    install_recommends: no
  with_items:
    - dmidecode
    - lshw
    - inxi
    - hwinfo

- name: run dmidecode
  shell: dmidecode > hard_dmidecode.log
  args:
    chdir: /tmp

- name: detect virtualization technology
  shell: systemd-detect-virt > hard_virt_tech.log
  args:
    chdir: /tmp

- name: run lscpu
  shell: lscpu > hard_lscpu.log
  args:
    chdir: /tmp

- name: run lsblk
  shell: lsblk -p > hard_lsblk.log
  args:
    chdir: /tmp

- name: run lshw
  shell: lshw > hard_lshw.log
  args:
    chdir: /tmp

- name: run inxi
  shell: inxi -Fxxx -c0 > hard_inxi.log
  args:
    chdir: /tmp

- name: run hwinfo
  shell: hwinfo > hard_hwinfo.log
  args:
    chdir: /tmp

- name: calculate sha512 checksums of logfiles
  stat:
    checksum_algorithm: sha512
    get_checksum: true
    get_attributes: false
    get_md5: false
    get_mime: false
    path: /tmp/{{item}}.log
  register: logfile
  with_items:
    - hard_dmidecode
    - hard_virt_tech
    - hard_lscpu
    - hard_lsblk
    - hard_lshw
    - hard_inxi
    - hard_hwinfo

- name: save checksums to files
  local_action:
    copy content="{{item.stat.checksum}}" dest="../logs/{{inventory_hostname}}/{{item.item}}.log.sha512"
  become: no
  with_items:
    - "{{ logfile.results }}"

- name: retrieve logs
  fetch:
    src: /tmp/{{item}}.log
    dest: ../logs/{{inventory_hostname}}/{{item}}.log
    flat: yes
  with_items:
    - hard_dmidecode
    - hard_virt_tech
    - hard_lscpu
    - hard_lsblk
    - hard_lshw
    - hard_inxi
    - hard_hwinfo

- name: remove dmidecode & lswh & inxi & hwinfo
  apt:
    name: "{{item}}"
    autoremove: yes
    purge: yes
    state: absent
  with_items:
    - dmidecode
    - lshw
    - inxi
    - hwinfo
